### ISSUE TITLE
StatsD client independence

### ISSUE THREAD

**Issue by lexmag** [jeffweiss/plug_statsd#4]
ExStatsD is just slow and most of the times [statsderl](https://github.com/lpgauth/statsderl) performs way better, there is even a new kid on the block [Statix](https://github.com/lexmag/statix).
How do you feel about making PlugStatsd independent of any StatsD client and provide configuration parameter for it?

**Comment by jeffweiss** [comment]
I'm open to it. What I may do is create different backends for each of the statsd clients, and then people can bring in the one they're interested in using.

**Comment by lexmag** [comment]
Different backends sounds good! I also think making a behaviour definition might be another way to achieve it.

**Comment by teodor-pripoae** [comment]
I implemented it in https://github.com/jeffweiss/plug_statsd/pull/5/

**Comment by jeffweiss** [comment]
Closed via #5
